version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: food_delivery_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: FoodDelivery
    networks:
      - food_delivery_network

  # Mongo Express - MongoDB Web UI
  mongo-express:
    image: mongo-express:latest
    container_name: food_delivery_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - food_delivery_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: food_delivery_backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/FoodDelivery
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-here}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - FRONTEND_URL=http://localhost:5174
    depends_on:
      - mongodb
    networks:
      - food_delivery_network
    volumes:
      - ./backend/uploads:/app/uploads

  # Customer Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: food_delivery_frontend
    restart: unless-stopped
    ports:
      - "5174:80"
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend
    networks:
      - food_delivery_network

  # Admin Panel
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: food_delivery_admin
    restart: unless-stopped
    ports:
      - "5175:80"
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend
    networks:
      - food_delivery_network

  # Restaurant Panel
  restaurant:
    build:
      context: ./restaurant
      dockerfile: Dockerfile
    container_name: food_delivery_restaurant
    restart: unless-stopped
    ports:
      - "5176:80"
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend
    networks:
      - food_delivery_network

networks:
  food_delivery_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
